<?php

session_start();

if (!isset($_SESSION['role']) || $_SESSION['role'] != 'admin') {
  header("Location: ../auth/login.php");
  exit;
}

require "../config/database.php";
require "../assets/fpdf/fpdf.php";

/* =====================================
   FILTER
===================================== */

$search = "";
$test = "";
$status = "";

if (isset($_GET['search'])) {
  $search = mysqli_real_escape_string($conn, $_GET['search']);
}

if (isset($_GET['test'])) {
  $test = mysqli_real_escape_string($conn, $_GET['test']);
}

if (isset($_GET['status'])) {
  $status = mysqli_real_escape_string($conn, $_GET['status']);
}

$where = "WHERE user_tests.status='finished'";

if ($search != "") {
  $where .= " AND (
        users.fullname LIKE '%$search%'
        OR users.email LIKE '%$search%'
    )";
}

if ($test != "") {
  $where .= " AND user_tests.test_id='$test'";
}

if ($status != "") {
  $where .= " AND user_tests.payment_status='$status'";
}

/* =====================================
   DATA
===================================== */

$query = mysqli_query($conn, "
SELECT
user_tests.*,
users.fullname,
users.email,
tests.title,
tests.price

FROM user_tests

JOIN users
ON users.id=user_tests.user_id

JOIN tests
ON tests.id=user_tests.test_id

$where

ORDER BY user_tests.created_at DESC
");

/* =====================================
   STATISTIK
===================================== */

$totalPeserta = mysqli_fetch_assoc(mysqli_query($conn, "
SELECT COUNT(DISTINCT user_id) total
FROM user_tests
"))['total'];

$totalTes = mysqli_fetch_assoc(mysqli_query($conn, "
SELECT COUNT(*) total
FROM user_tests
WHERE status='finished'
"))['total'];

$totalPendapatan = mysqli_fetch_assoc(mysqli_query($conn, "
SELECT SUM(tests.price) total

FROM user_tests

JOIN tests
ON tests.id=user_tests.test_id

WHERE payment_status='paid'
"))['total'];

$rata = mysqli_fetch_assoc(mysqli_query($conn, "
SELECT AVG(score) rata
FROM user_tests
WHERE status='finished'
"))['rata'];

/* =====================================
   PDF
===================================== */

$pdf = new FPDF('L', 'mm', 'A4');

$pdf->AddPage();

$pdf->SetTitle('Laporan Psikotes');

$pdf->SetFont('Arial', 'B', 18);
$pdf->Cell(0, 10, 'LAPORAN HASIL PSIKOTES', 0, 1, 'C');

$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 7, 'Tanggal Cetak : ' . date("d F Y H:i"), 0, 1, 'C');

$pdf->Ln(5);

/* =====================================
   RINGKASAN
===================================== */

$pdf->SetFont('Arial', 'B', 11);

$pdf->Cell(65, 8, 'Total Peserta', 1);
$pdf->Cell(35, 8, $totalPeserta, 1);

$pdf->Cell(65, 8, 'Tes Selesai', 1);
$pdf->Cell(35, 8, $totalTes, 1);

$pdf->Cell(65, 8, 'Rata-rata Nilai', 1);
$pdf->Cell(35, 8, round($rata), 1);

$pdf->Ln();

$pdf->Cell(65, 8, 'Total Pendapatan', 1);
$pdf->Cell(35, 8, 'Rp ' . number_format($totalPendapatan, 0, ",", "."), 1);

$pdf->Ln(15);

/* =====================================
   HEADER TABEL
===================================== */

$pdf->SetFont('Arial', 'B', 9);

$pdf->Cell(10, 8, 'No', 1, 0, 'C');
$pdf->Cell(45, 8, 'Peserta', 1);
$pdf->Cell(60, 8, 'Email', 1);
$pdf->Cell(55, 8, 'Tes', 1);
$pdf->Cell(20, 8, 'Nilai', 1, 0, 'C');
$pdf->Cell(20, 8, 'Benar', 1, 0, 'C');
$pdf->Cell(20, 8, 'Salah', 1, 0, 'C');
$pdf->Cell(30, 8, 'Pembayaran', 1, 0, 'C');
$pdf->Cell(35, 8, 'Tanggal', 1, 1, 'C');

$pdf->SetFont('Arial', '', 8);

$no = 1;

while ($row = mysqli_fetch_assoc($query)) {

  $pdf->Cell(10, 8, $no++, 1, 0, 'C');

  $pdf->Cell(45, 8, substr($row['fullname'], 0, 24), 1);

  $pdf->Cell(60, 8, substr($row['email'], 0, 34), 1);

  $pdf->Cell(55, 8, substr($row['title'], 0, 28), 1);

  $pdf->Cell(20, 8, $row['score'], 1, 0, 'C');

  $pdf->Cell(20, 8, $row['correct_answers'], 1, 0, 'C');

  $pdf->Cell(20, 8, $row['wrong_answers'], 1, 0, 'C');

  $pdf->Cell(30, 8, ucfirst($row['payment_status']), 1, 0, 'C');

  $pdf->Cell(35, 8, date("d/m/Y", strtotime($row['created_at'])), 1, 1, 'C');
}

/* =====================================
   FOOTER
===================================== */

$pdf->Ln(8);

$pdf->SetFont('Arial', 'I', 9);

$pdf->Cell(
  0,
  6,
  "Generated by PsychoTest System",
  0,
  1,
  'R'
);

$pdf->Output(
  'I',
  'Laporan_Psikotes_' . date('Ymd_His') . '.pdf'
);
